# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()
arr1d = np.array([1,2,3,4])


# Create a 2-dimensional NumPy array using np.array()
arr2d = np.array([[1,2], [3,4]])

# Create a 3-dimensional Numpy array using np.array()
arr3d = np.zeros((2,2,2))


array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [11]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print(arr1d.shape, " 1D shape")
print(arr1d.dtype, " 1D type")
print(arr1d.size, " 1D size")
print(arr1d.ndim, " 1D dimensions")
print(type(arr1d), " 1D type")



(4,)  1D shape
int64  1D type
4  1D size
1  1D dimensions
<class 'numpy.ndarray'>  1D type


In [12]:
# Attributes of 2-dimensional array
print(arr2d.shape, " 2D shape")
print(arr2d.dtype, " 2D type")
print(arr2d.size, " 2D size")
print(arr2d.ndim, " 2D dimensions")
print(type(arr2d), " 2D type")


(2, 2)  2D shape
int64  2D type
4  2D size
2  2D dimensions
<class 'numpy.ndarray'>  2D type


In [13]:
# Attributes of 3-dimensional array
print(arr3d.shape, " 3D shape")
print(arr3d.dtype, " 3D type")
print(arr3d.size, " 3D size")
print(arr3d.ndim, " 3D dimensions")
print(type(arr3d), " 3D type")


(2, 2, 2)  3D shape
float64  3D type
8  3D size
3  3D dimensions
<class 'numpy.ndarray'>  3D type


In [15]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
arrayFrame = pd.DataFrame(arr2d)
arrayFrame

0  1
0  1  2
1  3  4

In [17]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2), dtype=int)
ones

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [18]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [20]:
# Create an array within a range of 0 and 100 with step 3
evenRange = np.arange(0, 100, 3)
evenRange

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [22]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random2d = np.random.randint(10, size=(7,2))
random2d

array([[3, 0],
       [0, 5],
       [6, 7],
       [2, 7],
       [2, 3],
       [9, 0],
       [1, 4]])

In [24]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
randUniform = np.random.uniform(size=(3,5))
randUniform

array([[0.93492604, 0.95212085, 0.6737267 , 0.12204918, 0.66595287],
       [0.12722868, 0.64383744, 0.00352978, 0.47878763, 0.75923788],
       [0.55905848, 0.58730937, 0.00146378, 0.128361  , 0.27296588]])

In [27]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random2dSeed = np.random.randint(10, size=(4,6))
random2dSeed


array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [32]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
np.random.seed(None)
random2dNew = np.random.randint(10, size=(3,7))
# random2dNew


# Find the unique numbers in the array you just created
np.unique(random2dNew)

array([0, 1, 2, 3, 5, 6, 7, 8, 9])

In [33]:
# Find the 0'th index of the latest array you created
random2dNew[0]

array([7, 9, 0, 8, 6, 5, 2])

In [34]:
# Get the first 2 rows of latest array you created
random2dNew[:2]

array([[7, 9, 0, 8, 6, 5, 2],
       [2, 1, 1, 3, 6, 5, 7]])

In [35]:
# Get the first 2 values of the first 2 rows of the latest array
random2dNew[:2,:2]

array([[7, 9],
       [2, 1]])

In [36]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
randomArray = np.random.randint(10, size=(3,5))
onesArray = np.ones(shape=(3,5))

In [39]:
# Add the two arrays together
sumArray = randomArray + onesArray

In [40]:
# Create another array of ones of shape (5, 3)
newOnesArray = np.ones(shape=(5,3))

In [41]:
# Try add the array of ones and the other most recent array together
sumArray + newOnesArray

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [42]:
# Create another array of ones of shape (3, 5)
newOnes2Array = np.ones(shape=(3,5))

In [44]:
# Subtract the new array of ones from the other most recent array
randomArray - newOnes2Array

array([[ 3.,  3.,  4.,  6.,  5.],
       [ 0.,  2.,  3., -1.,  5.],
       [ 6.,  3.,  5.,  3.,  2.]])

In [46]:
# Multiply the ones array with the latest array
randomArray * newOnes2Array

array([[4., 4., 5., 7., 6.],
       [1., 3., 4., 0., 6.],
       [7., 4., 6., 4., 3.]])

In [47]:
# Take the latest array to the power of 2 using '**'
randomArray**2

array([[16, 16, 25, 49, 36],
       [ 1,  9, 16,  0, 36],
       [49, 16, 36, 16,  9]])

In [48]:
# Do the same thing with np.square()
np.square(randomArray)

array([[16, 16, 25, 49, 36],
       [ 1,  9, 16,  0, 36],
       [49, 16, 36, 16,  9]])

In [49]:
# Find the mean of the latest array using np.mean()
np.mean(randomArray)

4.266666666666667

In [50]:
# Find the maximum of the latest array using np.max()
np.max(randomArray)

7

In [51]:
# Find the minimum of the latest array using np.min()
np.min(randomArray)

0

In [52]:
# Find the standard deviation of the latest array
np.std(randomArray)

1.948218559493661

In [53]:
# Find the variance of the latest array
np.var(randomArray)

3.795555555555555

In [54]:
# Reshape the latest array to (3, 5, 1)
np.reshape(randomArray, (3,5,1))

array([[[4],
        [4],
        [5],
        [7],
        [6]],

       [[1],
        [3],
        [4],
        [0],
        [6]],

       [[7],
        [4],
        [6],
        [4],
        [3]]])

In [57]:
# Transpose the latest array
print(randomArray)
np.transpose(randomArray)

[[4 4 5 7 6]
 [1 3 4 0 6]
 [7 4 6 4 3]]


array([[4, 1, 7],
       [4, 3, 4],
       [5, 4, 6],
       [7, 0, 4],
       [6, 6, 3]])

What does the transpose do?

In [58]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
randIntArray = np.random.randint(0, 10, size=(3,3))
randInt2Array = np.random.randint(0,10, size=(3,2))

In [59]:
# Perform a dot product on the two newest arrays you created
np.dot(randIntArray, randInt2Array)

array([[30, 30],
       [52, 22],
       [36, 31]])

In [60]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
a1 = np.random.randint(0, 10, size=(4,3))
a2 = np.random.randint(0, 10, size=(4,3))

In [61]:
# Perform a dot product on the two newest arrays you created
np.dot(a1,a2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [62]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(a1, a2.T)

array([[108,  44,  75,  38],
       [ 45,  25,  38,  22],
       [ 36,  13,  38,  17],
       [144,  72, 116,  64]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [63]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a3 = np.random.randint(0, 10, size=(4,4))
a4 = np.random.randint(0, 10, size=(4,4))

In [64]:
# Compare the two arrays with '>'
a3 > a4

array([[False, False, False, False],
       [False,  True, False,  True],
       [False,  True, False, False],
       [False, False, False,  True]])

What happens when you compare the arrays with `>`?

In [65]:
# Compare the two arrays with '>='
a3 >= a4

array([[ True, False, False, False],
       [False,  True, False,  True],
       [False,  True, False, False],
       [False, False, False,  True]])

In [69]:
# Find which elements of the first array are greater than 7
a3 > 7

array([[False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [72]:
# Which parts of each array are equal? (try using '==')
a3 == a4

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [73]:
# Sort one of the arrays you just created in ascending order
np.sort(a3)

array([[0, 1, 1, 2],
       [3, 4, 5, 8],
       [1, 3, 6, 7],
       [2, 3, 4, 5]])

In [74]:
# Sort the indexes of one of the arrays you just created
np.argsort(a3)

array([[2, 0, 1, 3],
       [0, 2, 1, 3],
       [2, 0, 1, 3],
       [1, 3, 2, 0]])

In [75]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a3)

7

In [76]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a3)

2

In [78]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
print(a3)
print(np.argmax(a3, axis=1))

[[1 1 0 2]
 [3 5 4 8]
 [3 6 1 7]
 [5 2 4 3]]
[3 3 3 0]


In [79]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(a3, axis=0)

array([0, 0, 0, 0])

In [81]:
# Create an array of normally distributed random numbers
normallyDistributed = np.random.normal(size=(2,2))
normallyDistributed

array([[ 0.74678552, -0.18801917],
       [-0.61505712, -2.66329921]])

In [82]:
# Create an array with 10 evenly spaced numbers between 1 and 100
evenRange = np.linspace(1, 100, num=10)
evenRange

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.